spring:
    cloud:
        gateway:
            routes:
                - id: IMAGE-SERVICE
                  uri: lb://IMAGE-SERVICE
                  predicates:
                      - Path=/api/v1/images/**
                - id: MESSAGE-SERVICE
                  uri: lb://MESSAGE-SERVICE
                  predicates:
                      - Path=/api/v1/messages/**
                - id: PROFILE-SERVICE
                  uri: lb://PROFILE-SERVICE
                  predicates:
                      - Path=/api/v1/users/**
