# @format

spring:
  datasource:
    url: jdbc:h2:mem:ayush
  h2.console.enabled: true
  jpa:
    show-sql: true
jwt:
  secret_key: gttyvitvuntcutfbcitfctnvtnvvtntvtntyiit
  time_delta: 900000
  cookie_name: token
server:
  port: 8083
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka