# @format

spring:
  datasource:
    url: jdbc:h2:mem:ayush
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  jpa:
    show-sql: true
jwt:
  secret_key: gttyvitvuntcutfbcitfctnvtnvvtntvtntyiit
  time_delta: 900000
  cookie_name: token
  