# @format

spring:
    application:
        name: CONFIG-SERVER
    profiles:
        active: native
    cloud:
        config:
            fail-fast: true
            discovery:
                enabled: true
            #server:
            #    native:
            #        search-locations: ${userprofile}/Desktop/code/whatsapp-clone-microservices/config_server/config
server:
    port: 8085
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
